name: test

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
     - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
       
jobs:
  build:
    runs-on: namespace-profile-hyperledger-explorer
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: namespacelabs/nscloud-checkout-action@b8c45d632ce8118a5a0a51eb75a57cfccc74b8fa # v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        run: npm install

      - name: run test
        run: npm test
